# weights_kp: "models/SV_FT_TSWC_kp"
# weights_line: "models/SV_FT_TSWC_lines"
# pnl_refine: true
# device: "cuda:0"
# input_path: "examples/input/"
# output_path: "examples/output/"
# name: "FootDrone.jpg"
# input_type: "image"
# display: true

# # Start with low thresholds
# thresholds:
#   - kp_threshold: 0.15
#     line_threshold: 0.15


weights_kp: "models/SV_FT_TSWC_kp"
weights_line: "models/SV_FT_TSWC_lines"
device: "cuda:0"
input_path: "examples/input/"
output_path: "examples/output/"
name: "FootDrone.mp4"
input_type: "video"
display: false
pnl_refine: true
frame_step: 5  # Traiter une image sur 5
two_pass: true 

# Start with low thresholds
thresholds:
  - kp_threshold: 0.15
    line_threshold: 0.15